### ISSUE TITLE
Keyboard interface?

### ISSUE THREAD

**Issue by aarondall** [cathydeng/are-men-talking-too-much#1]
When the conversation is moving fast moving the mouse back and forth is a bit cumbersome. Is it possible to implement a keyboard interface so that pressing, say, d starts the dude timer and n switches to the nondude timer?

**Comment by wasokeli** [comment]
I'd go with arrow keys, since they're easy to find without looking (on most keyboards). <kbd>Left</kbd> for a dude, <kbd>right</kbd> for not a dude.

<kbd>F</kbd> and <kbd>J</kbd> are also easy to find without looking.

**Comment by cathydeng** [comment]
hey! I kept features to a minimum when building this, since I just wanted to make the simplest thing possible & get it out the door.

since this is a side project, I don't have the time/energy to implement feature requests. I do like this idea though, and am happy to review & merge if someone else wants to contribute! agree that left & right arrow would be best.

**Comment by cathydeng** [comment]
closed via #5
