### ISSUE TITLE
Include milliseconds?

### ISSUE THREAD

**Issue by timbuckley** [cathydeng/are-men-talking-too-much#14]
I think it will give more user feedback that button has indeed been clicked and the time is being recorded. Like a stopwatch. 

If you have milliseconds the percentage can change more gradually as well.

**Comment by cathydeng** [comment]
don't think milliseconds are worth the additional visual clutter; i styled the buttons to look 'pressed' on click so there's already some immediate user feedback. for the percentages to change more gradually I'd need to add decimal points, which imo are also not worth the visual clutter.

on a deeper level, I don't want to visually suggest that this site is about perfect accurate measurement (b/c a perfect measure of inclusion is impossible), which many people are already misinterpreting it to be. this site is just meant to be a provocation, & to nudge people to pay more attention to things that they otherwise may not notice.
