### ISSUE TITLE
Make a race version?

### ISSUE THREAD

**Issue by KirstieJane** [cathydeng/are-men-talking-too-much#18]
Hi @cathydeng! Firstly - thank you so much for building this little website!! I LOVE IT and I'm planning to use it a whole bunch 🙌 

It would be great to make a race one: "are white people talking too much".

What do you think? I could fork the project and create that version maybe? Figured I'd ask your opinion first :smile:

URGH - I suck - I see that you've said it's ok to steal and remix! I'll go ahead and fork away 🍴

**Comment by cathydeng** [comment]
hi Kirstie! you're absolutely free to use/remix as you please, but just wanted to add some loose thoughts:

- I didn't build anything about race b/c making assumptions about other peoples' identities gets into murky territory. assuming someone's gender can already be sorta icky, but I just made the judgment call that in most cases, identifying men vs everyone else is pretty straightforward. race gets trickier...
- I didn't intend for this tool to be a perfect metric of inclusion, since that's impossible (time talking is still such a crude metric, even if it's an improvement over counting bodies, & identity is so multi-faceted). instead of finding ways to hone measurement, I just went for the simplest tool possible - I designed this more as a provocation than as a scientific measuring tool. TBH this project probably spread the way it did b/c it's more provocation/rhetoric (it probably wouldn't have been as popular if it were called, say, genderinclusiontimer.com) so it's helpful to think of tech projects in those terms.

that being said, I'd encourage you play around and get creative! perhaps measuring things that are indirectly related to race, or having the subjects be public figures instead of private individuals, or keeping tabs on something that's more interesting than time, etc. I dunno! I'm sure there are tons of clever ways to highlight issues re: inclusion & race that I'm not thinking of. keep me posted on what you build!
