### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by loicmathey** [cathydeng/are-men-talking-too-much#6]
An app for android (and iphone of course)

Round button "+" to add a new button, it will ask to enter a name
Long click to add or remove the person to queue (for distribute speech)
(maybe a number on the buttons to see the queue)
Drag-out to delete a button

Sharing button to put the result online with a screenshot
Data download

Great idea :)

**Comment by owlboy** [comment]
On a mobile device it would be great to have the screen split into two hit-boxes so you can blind-tap them. Just know what end of the phone to tap for what and then you can feel where you need to tap.

**Comment by cathydeng** [comment]
hey! this issue is more of a separate project than a feature request.

in general, my opinion of mobile apps is that they are much less accessible than mobile-friendly websites, b/c apps require a download & b/c you can't use them on a laptop. realistically, people are very reluctant to download new mobile apps.

I'm also wary of adding a lot of features - I think the beauty of this idea is that it's dead simple & easy to use. In general, I think it's better for this to focus on aggregate patterns rather than individual behavior, & to focus on provoking conversation rather than perfect measurement on inclusion (which is impossible anyways)

that being said, you are more than welcome to steal this idea if you really want to build a mobile app. the screen split is a nice ui idea if this is mobile only.
